language: python

python:
- '2.7'
- '3.3'
- '3.4'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq pandoc

install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install .

script: ./build.sh

after_success: coveralls

deploy:
  - provider: pypi
    user: odi
    password:
      secure: MU3ZQ4rcpsXo0xIYSWXBfaKTAPn1IrL7AEcH231sseFV1RVmdC96Sfmtc2llvD9Eoc0KJpdW0Vy50azNqAMJwXCt/q3gagfao1PTnAEbklU+g1s2PTqW401E95Qm6w192WzWk/q0dy3SJwxEQt023QR78K+nEcYaCdLWDHjR2hY=
    on:
      tags: true
      all_branches: true
      python: 2.7
      repo: metaodi/osmapi
